# Generated by Django 4.1.5 on 2024-05-23 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rff_csb_project_one', '0002_vehicle_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasvehicle',
            old_name='gas_level_kg',
            new_name='level_kg',
        ),
        migrations.AddField(
            model_name='flexfuelvehicle',
            name='cng_capacity_kg',
            field=models.FloatField(default=-1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='flexfuelvehicle',
            name='cng_level_kg',
            field=models.FloatField(default=-1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='flexfuelvehicle',
            name='flex_fuel_type',
            field=models.CharField(choices=[('BE', 'Gasoline-Ethanol'), ('BG', 'Gasoline-CNG')], default='BE', max_length=2),
        ),
        migrations.AddField(
            model_name='flexfuelvehicle',
            name='fuel_capacity_l',
            field=models.FloatField(default=45, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='flexfuelvehicle',
            name='fuel_level_l',
            field=models.FloatField(default=22.5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='fuelvehicle',
            name='capacity_l',
            field=models.FloatField(default=45, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='fuelvehicle',
            name='fuel_level_l',
            field=models.FloatField(default=22.5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='midhybridvehicle',
            name='battery_capacity_kwh',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='midhybridvehicle',
            name='capacity_l',
            field=models.FloatField(default=45, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='midhybridvehicle',
            name='level_l',
            field=models.FloatField(default=22.5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pluginhybridvehicle',
            name='battery_capacity_kwh',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='pluginhybridvehicle',
            name='capacity_l',
            field=models.FloatField(default=45, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='pluginhybridvehicle',
            name='charge_level',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pluginhybridvehicle',
            name='level_l',
            field=models.FloatField(default=22.5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
