# Generated by Django 4.1.5 on 2024-05-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rff_csb_project_one', '0003_rename_gas_level_kg_gasvehicle_level_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='nickname',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
