# Generated by Django 4.1.5 on 2024-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rff_csb_project_one', '0004_alter_vehicle_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('EV', 'Electric Vehicle'), ('CGV', 'Compressed Gas Vehicle'), ('SFV', 'Single Fuel Vehicle'), ('FFVE', 'Flex Fuel Vehicle - Ethanol'), ('FFVG', 'Flex Fuel Vehicle - Gas'), ('MHEV', 'Mid Hybrid Vehicle'), ('PHEV', 'Plugin Hybrid Vehicle')], default='EV', max_length=4),
        ),
    ]
