# Generated by Django 4.1.5 on 2024-05-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rff_csb_project_one', '0007_vehicle_vehicle_type_shorthand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexfuelvehicle',
            name='flex_fuel_type_shorthand',
            field=models.CharField(choices=[('BE', 'Gasoline-Ethanol'), ('BG', 'Gasoline-CNG')], default='BE', max_length=2),
        ),
        migrations.AddField(
            model_name='fuelvehicle',
            name='fuel_type_shorthand',
            field=models.CharField(choices=[('D', 'Diesel'), ('E', 'Ethanol'), ('B', 'Gasoline')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='midhybridvehicle',
            name='fuel_type_shorthand',
            field=models.CharField(choices=[('D', 'Diesel'), ('B', 'Gasoline')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='pluginhybridvehicle',
            name='fuel_type_shorthand',
            field=models.CharField(choices=[('D', 'Diesel'), ('B', 'Gasoline')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='flexfuelvehicle',
            name='flex_fuel_type',
            field=models.CharField(choices=[('BE', 'Gasoline-Ethanol'), ('BG', 'Gasoline-CNG')], default='Gasoline-Ethanol', max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelvehicle',
            name='fuel_type',
            field=models.CharField(choices=[('D', 'Diesel'), ('E', 'Ethanol'), ('B', 'Gasoline')], default='Gasoline', max_length=10),
        ),
        migrations.AlterField(
            model_name='midhybridvehicle',
            name='fuel_type',
            field=models.CharField(choices=[('D', 'Diesel'), ('B', 'Gasoline')], default='Gasoline', max_length=10),
        ),
        migrations.AlterField(
            model_name='pluginhybridvehicle',
            name='fuel_type',
            field=models.CharField(choices=[('D', 'Diesel'), ('B', 'Gasoline')], default='Gasoline', max_length=10),
        ),
    ]
