# Generated by Django 4.1.5 on 2024-05-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rff_csb_project_one', '0008_flexfuelvehicle_flex_fuel_type_shorthand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refill',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
