# Generated by Django 4.1.5 on 2024-05-28 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rff_csb_project_one', '0009_rename_vehicle_id_refill_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='average_consumption',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='recharge',
            name='notes',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='recharge',
            name='recharge_location',
            field=models.CharField(default='Home', max_length=120),
        ),
        migrations.AddField(
            model_name='recharge',
            name='recharged_kwh',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='recharge',
            name='winter_tires',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refill',
            name='notes',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='refill',
            name='refill_location',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='refill',
            name='winter_tires',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='front_pressure',
            field=models.IntegerField(default=2.5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rear_pressure',
            field=models.IntegerField(default=2.5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='recommended_tire_pressure_front',
            field=models.IntegerField(default=2.5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='recommended_tire_pressure_rear',
            field=models.IntegerField(default=2.5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='running_on_winter_tires',
            field=models.BooleanField(default=False),
        ),
    ]
