# Generated by Django 4.1.5 on 2024-05-28 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rff_csb_project_one', '0011_alter_vehicle_front_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='fuel_level',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
